export * from './initializer-registration'
export * from './constructor-registration'
export * from './function-registration'
export * from './factory-registration'
export * from './static-registration'
export * from './registration'