export * from './create-constructor-registration'
export * from './create-function-registration'
export * from './create-factory-registration'
export * from './create-static-registration'
export * from './registration'